const { withAndroidStyles } = require('expo/config-plugins');

// Android draws its own translucent scrim behind the navigation buttons unless
// told otherwise, and `enforceNavigationBarContrast` defaults to **true** on
// API 29+. Deleting the item therefore changes nothing -- it has to be set to
// false explicitly.
//
// This only matters on Android 15+, where the bar is transparent and the app's
// own background shows through; the scrim would wash that colour out. Below 15
// the bar is opaque and coloured at runtime from the active theme, in App.tsx.
//
// styles.xml is regenerated by every prebuild, so this has to be a plugin
// rather than a hand edit.
const ITEM = 'android:enforceNavigationBarContrast';
const THEME = 'AppTheme';

function disableNavigationBarContrast(styles) {
  const theme = styles.resources?.style?.find((s) => s.$?.name === THEME);
  if (!theme) return styles;
  theme.item = theme.item ?? [];

  const existing = theme.item.find((i) => i.$?.name === ITEM);
  if (existing) {
    existing._ = 'false';
  } else {
    theme.item.push({
      _: 'false',
      $: { name: ITEM, 'tools:targetApi': '29' },
    });
  }
  return styles;
}

module.exports = function withTransparentNavigationBar(config) {
  return withAndroidStyles(config, (cfg) => {
    cfg.modResults = disableNavigationBarContrast(cfg.modResults);
    return cfg;
  });
};

module.exports.disableNavigationBarContrast = disableNavigationBarContrast;
